### ISSUE TITLE
关于drift

### ISSUE THREAD

**Issue by rmrf** [laincloud/lainctl#18]
lainctl/lain_admin_cli/drift.py line: 179 

```
if resp.status_code >= 300:
```

这里的判断，是否能涵盖所有可能的情况？

目前我遇到：
1， drift 到target 主机发出后，实际并未成功，但是返回说success: 而经过检查 container 依旧在原来的机器上。

2，line 190

```
output = check_output(['docker', '-H', 'swarm.lain:2376', 'inspect', drifted_container_name])
```

这个检查进入死循环，因为期望inspect 的drifted_container_name并未出现 (drift+1后的名字没有出现)

**Comment by panli889** [comment]
deployd 的执行结果是异步的，所以会马上返回结果，状态码小于300说明 deployd 已经接受请求了；
'container依旧在原来的机器上'，这个 container 是重新创建的容器还是原来的容器？
如果是原来的容器的话那应该是 deployd 出问题了；如果是重新创建的容器可能是 swarm 部署失败，能否看看 swarm 的日志？

**Comment by rmrf** [comment]
container是原来的容器，deployd并未采取行动。
的确是deployd出了问题，看来异步情况lainctl的确很难判断。

**Comment by panli889** [comment]
deployd 日志中能看出来出了什么问题么？挂了么？drift 过程会先把原来的容器删除再拉起新的容器，听起来执行删除操作失败了

**Comment by rmrf** [comment]
deployd并没有删除原容器。控制节点因为资源不足，deployd 没有正常工作，并出了一系列诡异问题，清理资源之后好了。
